apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
spec:
  selector:
    matchLabels:
      app: simple-webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      serviceAccountName: jenkins
      serviceAccount: jenkins
      containers:
        - name: simple-webapp
          image: docker.io/atwatanmalikm/webapp:2210150757
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-svc
spec:
  type: NodePort
  selector:
    app: simple-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001

